=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/FichiersXML/Emploi du temps/Emploi_de_temps.XSD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Eemploi_de_temps">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Filiere" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Jour" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Module" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Creneau" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Heure" type="xs:string"/>
                                                                <xs:element name="Prof" type="xs:string"/>
                                                                <xs:element name="Salle" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="type" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="CM"/>
                                                                        <xs:enumeration value="TD"/>
                                                                        <xs:enumeration value="TP"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nom" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nom" type="xs:string" use="required"/>
                                    <xs:attribute name="date" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nom" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/Fichiers XML/Emploi du temps/Emploi_du_temps.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Eemploi_de_temps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Emploi_de_temps.XSD">
    <Filiere nom="ginf2">
        <Jour date="XX/XX" nom="Lundi">
            <Module nom="Cryptoraphie">
                <Creneau type="CM">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>LAZAAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Cryptoraphie">
                <Creneau type="CM">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>LAZAAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Bases de donnes non SQL">
                <Creneau type="CM">
                    <Heure>13:30 - 15:00</Heure>
                    <Prof>BADIR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Bases de donnes non SQL">
                <Creneau type="TP">
                    <Heure>15:30 - 17:00</Heure>
                    <Prof>BADIR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
        </Jour>
        <Jour date="XX/XX" nom="Mardi">
            <Module nom="Programmation Decl">
                <Creneau type="TP">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>CHAFIK</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Programmation Decl">
                <Creneau type="TP">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>CHAFIK</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Programmation Decl">
                <Creneau type="CM">
                    <Heure>13:30 - 15:00</Heure>
                    <Prof>EL ALAMI</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
        </Jour>
        <Jour date="XX/XX" nom="Mercredi">
            <Module nom="Traitement d'image">
                <Creneau type="TP">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>LACHKAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Traitement d'image">
                <Creneau type="CM">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>LACHKAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Management de projets">
                <Creneau type="TP">
                    <Heure>13:30 - 15:00</Heure>
                    <Prof>RAHALI AZOUZI</Prof>
                    <Salle>Salle B19</Salle>
                </Creneau>
            </Module>
            <Module nom="Management de projets">
                <Creneau type="TP">
                    <Heure>15:30 - 17:00</Heure>
                    <Prof>RAHALI AZOUZI</Prof>
                    <Salle>Salle B19</Salle>
                </Creneau>
            </Module>
        </Jour>
        <Jour date="XX/XX" nom="Jeudi">
            <Module nom="Traitement d'image">
                <Creneau type="TP">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>LACHKAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Traitement d'image">
                <Creneau type="CM">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>LACHKAR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Dot Net  C sharp">
                <Creneau type="TP">
                    <Heure>13:30 - 15:00</Heure>
                    <Prof>GHAILANI</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Dot Net  C sharp">
                <Creneau type="TP">
                    <Heure>15:30 - 17:00</Heure>
                    <Prof>GHAILANI</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
        </Jour>
        <Jour date="XX/XX" nom="Vendredi">
            <Module nom="Gestion des donnees">
                <Creneau type="CM">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>BADIR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Gestion des donnees">
                <Creneau type="CM">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>BADIR</Prof>
                    <Salle>Salle B20</Salle>
                </Creneau>
            </Module>
            <Module nom="Comptabilite 2">
                <Creneau type="CM">
                    <Heure>14:30 - 16:00</Heure>
                    <Prof>Naitboubker</Prof>
                    <Salle>Salle B2</Salle>
                </Creneau>
            </Module>
            <Module nom="Comptabilite 2">
                <Creneau type="CM">
                    <Heure>16:30 - 18:00</Heure>
                    <Prof>Naitboubker</Prof>
                    <Salle>Salle B2</Salle>
                </Creneau>
            </Module>
        </Jour>
    </Filiere>
</Eemploi_de_temps>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/fichierXML/Eemploi_de_temps/Emploi_de_temps.xml
<?xml version="1.0" encoding="UTF-8"?>
<Eemploi_de_temps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Emploi_de_temps.XSD">

    <Filiere nom="ginf2">
        <Jour nom="Lundi" date="02/01">
            <Module nom="xml">
                <Creneau type="TD">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>Mohamed Halli</Prof>
                    <Salle>B12</Salle>
                </Creneau>
                <Creneau type="TD">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>Mohamed Halli</Prof>
                    <Salle>B12</Salle>
                </Creneau>
            </Module>
        </Jour>
        <Jour nom="Mardi" date="03/01">
            <Module nom="xml">
                <Creneau type="TD">
                    <Heure>09:00 - 10:30</Heure>
                    <Prof>Mohamed Halli</Prof>
                    <Salle>B12</Salle>
                </Creneau>
                <Creneau type="TD">
                    <Heure>11:00 - 12:30</Heure>
                    <Prof>Mohamed Halli</Prof>
                    <Salle>B12</Salle>
                </Creneau>
            </Module>
        </Jour>
    </Filiere>

</Eemploi_de_temps>
