=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/fichierXML/Module/sous_modules.DTD
<!ELEMENT Sous_modules (Sous_Module+)>
<!ELEMENT Sous_Module (Nom, Code, Module, Professeur)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Code (#PCDATA)>
<!ELEMENT Module (#PCDATA)>
<!ELEMENT Professeur (#PCDATA)>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/fichierXML/Module/sous_modules.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Sous_modules SYSTEM "sous_modules.dtd">

<Sous_modules>
    <Sous_Module>
        <Nom>JAVA</Nom>
        <Code>GINF32</Code>
        <Module>POO</Module>
        <Professeur>Mohamed Haddad</Professeur>
    </Sous_Module>

    <Sous_Module>
        <Nom>Python</Nom>
        <Code>GINF33</Code>
        <Module>Data Science</Module>
        <Professeur>Fatima Zahra El Idrissi</Professeur>
    </Sous_Module>
</Sous_modules>
