=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/Fichiers_XQuery/affichage_module_result_avec_Xquery/Affichage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- Élément racine -->
    <xs:element name="Module">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etudiant" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CodeApogee" type="xs:int"/>
                            <xs:element name="Nom" type="xs:string"/>
                            <xs:element name="Prenom" type="xs:string"/>
                            <xs:element name="DateNaissance" type="xs:date"/>
                            <xs:element name="SousModule" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Note" type="xs:decimal"/>
                                    </xs:sequence>
                                    <xs:attribute name="nom" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nom" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/Fichiers_XQuery/affichage_module_result_avec_Xquery/Affichage_GINF33.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        nom="Modelisation orientée objet et IHM"
        xsi:noNamespaceSchemaLocation="Affichage.xsd">
   <Etudiant>
      <CodeApogee>21010278</CodeApogee>
      <Nom>ABDELOUAHAB</Nom>
      <Prenom>SOUFIANE</Prenom>
      <DateNaissance>2001-09-25</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>13</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>11</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21011326</CodeApogee>
      <Nom>ABOU-EL KASEM</Nom>
      <Prenom>KENZA</Prenom>
      <DateNaissance>2003-05-21</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>13</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>20</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>19</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010358</CodeApogee>
      <Nom>AHMYTTOU</Nom>
      <Prenom>AYA</Prenom>
      <DateNaissance>2004-02-23</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>12</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>17</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>12</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010266</CodeApogee>
      <Nom>AIDOUN</Nom>
      <Prenom>IBTISSAM</Prenom>
      <DateNaissance>2002-09-14</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>20</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>16</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>20001758</CodeApogee>
      <Nom>AL AZAMI</Nom>
      <Prenom>TAREK</Prenom>
      <DateNaissance>2001-02-23</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>19</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>19</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>14</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010287</CodeApogee>
      <Nom>ALLAM</Nom>
      <Prenom>ELARBI</Prenom>
      <DateNaissance>2004-02-27</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>16</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>18</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010482</CodeApogee>
      <Nom>ARIB</Nom>
      <Prenom>AYMANE</Prenom>
      <DateNaissance>2003-09-25</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>13</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>12</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21009157</CodeApogee>
      <Nom>AZZMAN</Nom>
      <Prenom>NORELIMANE</Prenom>
      <DateNaissance>2003-09-26</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>14</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>17</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010356</CodeApogee>
      <Nom>AZZOUZ</Nom>
      <Prenom>CHAIMAE</Prenom>
      <DateNaissance>2004-01-31</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>14</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>12</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>12</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010411</CodeApogee>
      <Nom>BEN IMRAN</Nom>
      <Prenom>AHLAM</Prenom>
      <DateNaissance>2003-10-27</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>13</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>20</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010476</CodeApogee>
      <Nom>BENCHINE</Nom>
      <Prenom>ABDELILAH</Prenom>
      <DateNaissance>2003-12-31</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>20</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>12</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>19</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>22012817</CodeApogee>
      <Nom>BENMGUIRIDA</Nom>
      <Prenom>ANAS</Prenom>
      <DateNaissance>2000-12-18</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>10</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>20</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>19</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21009110</CodeApogee>
      <Nom>BERKOUKT</Nom>
      <Prenom>AMINE</Prenom>
      <DateNaissance>2004-05-13</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>5</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>16</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>17</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21011779</CodeApogee>
      <Nom>BIGAGANE</Nom>
      <Prenom>ABDELLAH</Prenom>
      <DateNaissance>2004-01-13</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>6</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>4</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>15</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>20011005</CodeApogee>
      <Nom>BOUHNINE</Nom>
      <Prenom>SAFAA</Prenom>
      <DateNaissance>2001-12-28</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>17</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>8</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21002603</CodeApogee>
      <Nom>BOUKER</Nom>
      <Prenom>MOHAMMED</Prenom>
      <DateNaissance>2003-07-19</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>10</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>10</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>10</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010261</CodeApogee>
      <Nom>BOULERBAH</Nom>
      <Prenom>YASSER</Prenom>
      <DateNaissance>2003-09-13</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>19</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21011724</CodeApogee>
      <Nom>BOUNOUAR</Nom>
      <Prenom>MOHAMMED</Prenom>
      <DateNaissance>2003-12-15</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>11</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>14</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21009025</CodeApogee>
      <Nom>BOUSSAID</Nom>
      <Prenom>MERYEME</Prenom>
      <DateNaissance>2003-05-10</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>4</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>13</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>8</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010326</CodeApogee>
      <Nom>CHAIBERRAS</Nom>
      <Prenom>SOUHAIL</Prenom>
      <DateNaissance>2003-04-17</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>12</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>17</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>17</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010299</CodeApogee>
      <Nom>CHERKI</Nom>
      <Prenom>HOUSSAM</Prenom>
      <DateNaissance>2003-04-20</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>14</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>18</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>17</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21009475</CodeApogee>
      <Nom>DAHBI</Nom>
      <Prenom>MOAD</Prenom>
      <DateNaissance>2003-09-03</DateNaissance>
      <SousModule nom="Modelisation orientée objet UML">
         <Note>12</Note>
      </SousModule>
      <SousModule nom="IHM">
         <Note>15</Note>
      </SousModule>
      <SousModule nom="Cycle de Vie logiciel">
         <Note>18</Note>
      </SousModule>
   </Etudiant>
   <Etudiant>
      <CodeApogee>21010439</CodeApogee>
