=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/FichiersXML/Module/Modules.dtd
<!ELEMENT Modules (Module+)>
<!ELEMENT Module (SousModule+)>

<!ATTLIST Module nom CDATA #REQUIRED>
<!ATTLIST Module code CDATA #REQUIRED>

<!ELEMENT SousModule (Nom)>
<!ELEMENT Nom (#PCDATA)>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/FichiersXML/Module/Modules.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Modules SYSTEM "Modules.dtd">

<Modules>
    <Module nom="POO" code="GINF32">
        <SousModule>
            <Nom>JAVA</Nom>
        </SousModule>
        <SousModule>
            <Nom>C++</Nom>
        </SousModule>
    </Module>
    <Module nom="Data Science" code="GINF31">
        <SousModule>
            <Nom>Python</Nom>
        </SousModule>
        <SousModule>
            <Nom>Theorie des graphes</Nom>
        </SousModule>
    </Module>
</Modules>
