=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/fichierXML/Professeur/Professeurs.DTD
<!ELEMENT Professeurs (Professeur+)>
<!ELEMENT Professeur (Nom, Prenom, Email, Telephone, Departement)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Departement (#PCDATA)>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/Fichiers XML/Professeur/Professeurs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Professeurs SYSTEM "Professeurs.dtd">

<Professeurs>
    <Professeur>
        <Nom>ABETIOU</Nom>
        <Prenom>SOFIANE</Prenom>
        <Email>ABETIOU.SOFIANE@uae.ac.ma</Email>
        <Telephone>0767366306</Telephone>
        <Departement>Informatique</Departement>
    </Professeur>

    <Professeur>
        <Nom>EL AMRANI</Nom>
        <Prenom>YASSINE</Prenom>
        <Email>YASSINE.ELAMRANI@uae.ac.ma</Email>
        <Telephone>0612345678</Telephone>
        <Departement>RÃ©seaux</Departement>
    </Professeur>
</Professeurs>
