=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/FichiersXML/Note/Notes.DTD
<!ELEMENT Notes (Note+)>
<!ELEMENT Note (CodeApogee, ModuleCode, SousModule,Moyenne)>
<!ELEMENT ModuleCode (#PCDATA)>
<!ELEMENT SousModule (#PCDATA)>
<!ELEMENT CodeApogee (#PCDATA)>
<!ELEMENT Moyenne (#PCDATA)>

=== MohamedSakhri1/Ecole-XML-Java/src/main/resources/FichiersXML/Note/Notes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Notes SYSTEM "Notes.dtd">

<Notes>
    <Note>
        <CodeApogee>2000073</CodeApogee>
        <ModuleCode>GINF32</ModuleCode>
        <SousModule>JAVA</SousModule>
        <Moyenne>15</Moyenne>
    </Note>
    <Note>
        <CodeApogee>2000073</CodeApogee>
        <ModuleCode>GINF32</ModuleCode>
        <SousModule>C++</SousModule>
        <Moyenne>19</Moyenne>
    </Note>
    <Note>
        <CodeApogee>2000077</CodeApogee>
        <ModuleCode>GINF32</ModuleCode>
        <SousModule>JAVA</SousModule>
        <Moyenne>20</Moyenne>
    </Note>
    <Note>
        <CodeApogee>2000077</CodeApogee>
        <ModuleCode>GINF32</ModuleCode>
        <SousModule>C++</SousModule>
        <Moyenne>20</Moyenne>
    </Note>
    <Note>
        <CodeApogee>2000073</CodeApogee>
        <ModuleCode>GINF33</ModuleCode>
        <SousModule>Python</SousModule>
        <Moyenne>13</Moyenne>
    </Note>
</Notes>
